from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


def _require_python_312() -> None:
    if sys.version_info < (3, 12):
        msg = (
            "gate.py requires Python >= 3.12.\n"
            "Run via uv:\n"
            "  uv run --python 3.12 devtools/gate.py\n"
        )
        raise SystemExit(msg)


@dataclass(frozen=True)
class GateConfig:
    repo_root: Path
    check: bool
    tests: bool
    build: bool


def _run(cmd: list[str], *, cwd: Path) -> None:
    subprocess.run(cmd, cwd=cwd, check=True)


def _git_ls_files(*, repo_root: Path) -> list[Path]:
    result = subprocess.run(
        [
            "git",
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
        ],
        cwd=repo_root,
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    files: list[Path] = []
    for line in result.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        files.append(repo_root / line)
    return files


def _is_owned_source(path: Path, *, repo_root: Path) -> bool:
    rel = path.relative_to(repo_root).as_posix()
    if rel.startswith(("node_modules/", "dist/", ".venv/", ".git/")):
        return False
    if rel.startswith("drizzle/meta/"):
        # Generated by schema tooling; owned schema lives in drizzle/schema.ts and migrations.
        return False
    if not path.is_file():
        return False
    # Guardrails are for owned *runtime* artifacts; documentation must not be size/line constrained.
    return path.suffix in {".ts", ".tsx", ".js", ".jsx", ".css", ".py", ".sql", ".json"}


def _check_file_guardrails(*, repo_root: Path) -> None:
    max_lines = 500
    max_bytes = 18_000

    oversized: list[str] = []

    for path in _git_ls_files(repo_root=repo_root):
        if not _is_owned_source(path, repo_root=repo_root):
            continue

        data = path.read_bytes()
        size = len(data)
        lines = data.count(b"\n") + 1
        if lines > max_lines or size > max_bytes:
            rel = path.relative_to(repo_root).as_posix()
            oversized.append(f"{rel} (lines={lines}, bytes={size})")

    if oversized:
        joined = "\n".join(f"- {item}" for item in oversized)
        raise SystemExit(
            "Owned-file guardrails violated (must be <= 500 lines and <= 18kB):\n" + joined
        )


def _check_drizzle_squashed_init(*, repo_root: Path) -> None:
    drizzle_dir = repo_root / "drizzle"
    if not drizzle_dir.is_dir():
        return

    sql_files = sorted(path.name for path in drizzle_dir.glob("*.sql") if path.is_file())
    expected = ["0000_init.sql"]
    if sql_files != expected:
        raise SystemExit(
            "Pre-release DB posture violated: expected a single squashed init migration.\n"
            f"Expected: {expected}\n"
            f"Found: {sql_files}\n"
            "Fix: squash to drizzle/0000_init.sql and delete any other drizzle/*.sql migrations."
        )

    journal_path = drizzle_dir / "meta" / "_journal.json"
    if not journal_path.is_file():
        raise SystemExit(
            "Missing drizzle journal file (required for deterministic migrations): drizzle/meta/_journal.json"
        )

    try:
        journal = json.loads(journal_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Failed to parse drizzle journal JSON: {journal_path.as_posix()} ({exc})")

    entries = journal.get("entries")
    if not isinstance(entries, list):
        raise SystemExit("drizzle/meta/_journal.json must contain an 'entries' list")
    if len(entries) != 1 or entries[0].get("tag") != "0000_init":
        raise SystemExit(
            "Pre-release DB posture violated: drizzle/meta/_journal.json must contain only the 0000_init entry.\n"
            f"Found entries: {entries}"
        )


def main(argv: list[str]) -> int:
    _require_python_312()

    parser = argparse.ArgumentParser()
    parser.add_argument("--no-check", action="store_true", help="Skip TypeScript typecheck")
    parser.add_argument("--no-tests", action="store_true", help="Skip tests")
    parser.add_argument("--no-build", action="store_true", help="Skip production build")
    args = parser.parse_args(argv)

    repo_root = Path(__file__).resolve().parent.parent

    os.environ.setdefault("CI", "1")

    config = GateConfig(
        repo_root=repo_root,
        check=not args.no_check,
        tests=not args.no_tests,
        build=not args.no_build,
    )

    _check_file_guardrails(repo_root=config.repo_root)
    _check_drizzle_squashed_init(repo_root=config.repo_root)

    if config.check:
        _run(["pnpm", "run", "check"], cwd=config.repo_root)
    if config.tests:
        _run(["pnpm", "test"], cwd=config.repo_root)
    if config.build:
        _run(["pnpm", "run", "build"], cwd=config.repo_root)

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
